language: objective-c
rvm: 2.2.2
before_install:
    - gem install cocoapods
podfile: Example/Podfile
script: xctool -workspace Example/FLUX.xcworkspace -scheme FLUX-Example build test -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
