language: objective-c
rvm: 2.2.2
before_install: gem update bundler
install: travis_wait bundle install
before_script: cd Example && pod install 
script: xctool -workspace FLUX.xcworkspace -scheme FLUX-Example build test -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
