language: objective-c
rvm: 2.2.2
osx_image: xcode7.3
before_install: gem update bundler
install: bundle install
before_script: cd Example && pod install 
script: xcodebuild -workspace FLUX.xcworkspace -scheme FLUX-Example build test -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
